server:
  port: 7778
spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://123.56.66.208:3306/littlelittleweb?characterEncoding=utf-8
    username: root
    password: FjlPyf6666@  #假的
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 123.56.66.208
      database: 0
      password: 123456
      port: 6379

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto