server:
  port: 7778
spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://123.56.66.208:3306/littlelittleweb?characterEncoding=utf-8
    username: root
    password: FjlPyf6666@  #假的
    driver-class-name: com.mysql.cj.jdbc.Driver
    #以下为连接池的相关参数配置
    dbcp2:
      max-idle: 10
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5
      validation-query: 'SELECT 1'
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800

  data:
    redis:
      host: 123.56.66.208
      database: 0
      password: 123456
      port: 6379

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto